### ISSUE TITLE
Possibility for user-control on the order of the dialogues/coaches

### ISSUE THREAD

**Issue by DanielPD** [AgentsUnited/topic-selection-engine#9]
Discuss about possibilities for more direct control from the user on the overarching order in which interacting with coaches. This will influence the pre-scripted or rule-based ordering of dialogues.

For example, a user should always have an introduction with all coaches before moving on to goalsetting. But the order in which the coaches introduce themselves may be chosen by the user.

**Comment by tbeinema** [comment]
Functionality for scripted topic selection has been added. Users can now also define a balance between scripted and automatic topic selection.
